# -*- coding: utf-8 -*-
"""302

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfOrzqz-m5X83uyzkC7LvQHX8CfO2pgm
"""

monk_fish_team=[158,157,163,157,145]

total=sum(monk_fish_team)
length=len(monk_fish_team)
mean=total/length
variance=0
for height in monk_fish_team:
  variance += (height-mean)**2

variance = variance/length
print('分散',variance)
variance=variance**0.5
print('標準偏差は',variance)