# -*- coding: utf-8 -*-
"""304

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfOrzqz-m5X83uyzkC7LvQHX8CfO2pgm
"""

sum=0
for i in range(2,10):
  sum+=i
print(sum)