# -*- coding: utf-8 -*-
"""ex5a

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPwJKsURKcB4tzDCS7rq3dtjy0f4_MUu
"""

a=input("Input a string: ")
b=input("Input a word: ")
if b in a:
  print("Yes")
else:
  print("No")