# -*- coding: utf-8 -*-
"""ex5b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPwJKsURKcB4tzDCS7rq3dtjy0f4_MUu
"""

a=int(input("Input num: "))
b=int(input("Input maximum: "))
c=1
for i in range(1,b+1):
  c *= i
  if c >= b:
    print(i)
    print(c)
    break