# -*- coding: utf-8 -*-
"""ex1a

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkxuEGcDT26lzeH7wXD5FDw6uWm4e5C7
"""

m = 15
n = 4
print(m / n)
print(m % n)