# -*- coding: utf-8 -*-
"""ex1b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkxuEGcDT26lzeH7wXD5FDw6uWm4e5C7
"""

pi = 3.141592
diameter = 12756.274
print(pi * diameter)
print(pi * (diameter/2)**2)