# -*- coding: utf-8 -*-
"""ex2c

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0bRYCskS_CAJ2yVaF8arbcASAKnU6TN
"""

k=input()
n=int(input())


s=k*n
print(s)