# -*- coding: utf-8 -*-
"""ex1c

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QkxuEGcDT26lzeH7wXD5FDw6uWm4e5C7
"""

cal_per_1kg = 7200
cal_per_1minjog = 7.76
min_to_lose1kg = cal_per_1kg / cal_per_1minjog
hours_to_lose1kg = min_to_lose1kg / 60
print(hours_to_lose1kg)