# -*- coding: utf-8 -*-
"""ex2b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0bRYCskS_CAJ2yVaF8arbcASAKnU6TN
"""

k=input()
l=input()
print(k+" "+l+"!")