# -*- coding: utf-8 -*-
"""ex2d

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D0bRYCskS_CAJ2yVaF8arbcASAKnU6TN
"""

r=float(input())
pi=3.14
print(pi*r**2)