# -*- coding: utf-8 -*-
"""101

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfOrzqz-m5X83uyzkC7LvQHX8CfO2pgm
"""

day = 24
str_day=str(day)
date=str_day+"日"
print(date)