# -*- coding: utf-8 -*-
"""ex3a

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fBtn9QhbCBC7yZodWdlGNi33tIWcRtN
"""

num = int(input("Input an integer: "))
a=[10,20,30,num]
print(a)
x=max(a)
y=min(a)
z=sum(a)
print("max:", x)
print("min:", y)
print("sum:", z)