# -*- coding: utf-8 -*-
"""ex4a

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPwJKsURKcB4tzDCS7rq3dtjy0f4_MUu
"""

a=int(input("Input an integer #1: "))
b=int(input("Input an integer #2: "))
for n in range(a,b+1):
  c=n**2
  print(c)