# -*- coding: utf-8 -*-
"""ex4a

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPwJKsURKcB4tzDCS7rq3dtjy0f4_MUu
"""

N=int(input("Input N: "))

for n in range(1,N+2):
  a=(7/9)*(-2)**(n-1)+(n/3)-(1/9)
  an=round(a)
  print("a"+str(n-1)+"="+str(an))