# -*- coding: utf-8 -*-
"""301

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfOrzqz-m5X83uyzkC7LvQHX8CfO2pgm
"""

mcz=['れに','かなこ','しおり','あやか','ももか']
for member in mcz:
  print(member)