# -*- coding: utf-8 -*-
"""303

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PfOrzqz-m5X83uyzkC7LvQHX8CfO2pgm
"""

savings=100
for i in range(15):
  savings+=savings*0.05
print('５％金利の場合15年で',savings,'円')