# -*- coding: utf-8 -*-
"""ex3b

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fBtn9QhbCBC7yZodWdlGNi33tIWcRtN
"""

import random
x = random.sample(list(range(0, 20)), k=6)
print(x)
print(x[4:]+x[:4])