# -*- coding: utf-8 -*-
"""ex3c

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17fBtn9QhbCBC7yZodWdlGNi33tIWcRtN
"""

import random
x = random.sample(list(range(0, 20)), k=random.randint(5, 10))
print(x)
y=len(x)
z=sum(x)
print("num: ",y)
print("sum: ",z)
print("ave: ",z/y)

