# -*- coding: utf-8 -*-
"""ex4d

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPwJKsURKcB4tzDCS7rq3dtjy0f4_MUu
"""

import random
n = random.randint(2, 5)
print("n =", n)

x=[]
a=0
b=0
for i in range(n):
  A=float(input("number "+ str(i+1) +": "))
  x+=[A]
  a+=A
  b+=A**2
B=b/n
C=(a/n)**2
print(x)
print("ave = "+ str(a/n))
print("std = "+ str((B-C)**0.5))